# Mimir single-binary configuration based on official documentation
# https://grafana.com/docs/mimir/latest/configure/configuration-parameters/

target: all

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks

ingester:
  ring:
    replication_factor: 1

compactor:
  data_dir: /tmp/mimir-compactor

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/rules

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /data/alertmanager

multitenancy_enabled: false

usage_stats:
  enabled: false