apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopmicro
  labels:
    app: backend
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: application
    spec:
      containers:
      - name: backend
        image: shopmicro-backend:latest
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: POSTGRES_URL
          value: "postgresql://postgres:postgres@postgres:5432/shopmicro"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: OTEL_SERVICE_NAME
          value: "shopmicro-backend"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://alloy:4318/v1/traces"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 3001
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopmicro
  labels:
    app: backend
    tier: application
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP
