apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: shopmicro
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 15s
          queryTimeout: 300s
          httpMethod: GET
          prometheusType: Mimir
          prometheusVersion: 2.40.0
          cacheLevel: 'High'
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          maxLines: 1000
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance']
          tracesToMetrics:
            datasourceUid: 'mimir'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: shopmicro
  labels:
    app: grafana
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        tier: monitoring
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_AUTO_ASSIGN_ORG
          value: "true"
        - name: GF_USERS_AUTO_ASSIGN_ORG_ID
          value: "1"
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: "Admin"
        - name: GF_SERVER_ROOT_URL
          value: "http://localhost:3000"
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: shopmicro
  labels:
    app: grafana
    tier: monitoring
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana
  type: ClusterIP
