# Loki single-binary configuration based on official documentation
# https://grafana.com/docs/loki/latest/configuration/

server:
  http_listen_port: 3100

auth_enabled: false

common:
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-shipper-active
    cache_location: /tmp/loki/tsdb-shipper-cache
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_global_streams_per_user: 5000
  max_query_length: 721h
  max_query_parallelism: 32
  max_streams_per_user: 0
  max_line_size: 0

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 100

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  log_queries_longer_than: 5s

query_scheduler:
  max_outstanding_requests_per_tenant: 256

ingester:
  wal:
    enabled: true
    dir: /tmp/loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

compactor:
  working_directory: /tmp/loki/compactor
